import { generateToken } from "@test/utils/helpers";
import AuthMiddleware, { AuthRequest } from "@middlewares/authmiddleware";

describe("AuthMiddleware", () => {
  it("accepts a token generated by test helpers", () => {
    const req = {
      headers: { authorization: `Bearer ${generateToken("user-id", 3, "company-1")}` },
    } as AuthRequest;
    const json = jest.fn();
    const res = { status: jest.fn().mockReturnValue({ json }) } as any;
    const next = jest.fn();

    AuthMiddleware(req, res, next);

    expect(next).toHaveBeenCalledTimes(1);
    expect(req.user).toMatchObject({ userId: "user-id", role: 3, company_id: "company-1" });
    expect(res.status).not.toHaveBeenCalled();
  });
});
